### ISSUE TITLE
安装必须使用admin

### ISSUE THREAD

**Issue by xuanyuanaosheng** [yp-app/pandora#2]
我司电脑个人没有admin权限，能提供免admin安装的windows版本么？

**Comment by yp-app** [comment]
[Windows版免安装下载地址](https://pandoraicu.obs.cn-north-4.myhuaweicloud.com/Pandora%20Windows%E5%85%8D%E5%AE%89%E8%A3%85%E7%89%88.zip)

**Comment by xuanyuanaosheng** [comment]
感谢~
